spring:
  application:
    name: backend

  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
